framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # Redis transport with Streams (valid options only)
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
                    delay: 1000
            
            transaction_processing:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    stream: transaction_processing
                    group: transaction_processors
                    consumer: processor_1
                retry_strategy:
                    max_retries: 5
                    delay: 2000
                    multiplier: 3
                    max_delay: 30000
            
            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - doctrine_transaction

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\ProcessTransactionMessage: transaction_processing
            App\Message\TransactionCompletedEvent: async
            App\Message\TransactionFailedEvent: async

